text1 = """Pandora qSHIELD is an utility tool that enables end-users to effortlessly back up and restore their qBittorrent data.\n\nqSHIELD also contains a logging system to assist you in diagnosing any issues that hampered your backup and restore process. Rest assured that the tool’s source code contains no programming that would transmit information to third parties.\n\nFor any questions, queries or to report any detected bugs, contact us at: pandoradynamics@gmail.com\n\nⓒ2024-2026 Pandora Dynamics, RyanCantrell321. All Rights Reserved!\nAlgorithms related to framework dependency threadings and the logger system have been extensively refined by Amazon's Amazon Q® and OpenAI's ChatGPT®\n\nPandora qSHIELD is safeguarded by propietary license."""

text2 = """For backup purposes, this software is designed to automatically retrieve data from the following folders: "%localappdata%/qBittorrent" and "%appdata%/qBittorrent" after you click the "Backup Data" button.\n\nYou can choose the destination folder and partition for storing the backup. Ensure you have noted the drive letters of your Windows operating system.\n\nAfter you click the "Start Backup" button and have specified the location, you will find a "qSHIELD_Qbt_Backup {Date}.zip" file there which you will need to specify during the restoration process. If you haven't specified the backup location, qSHIELD will use the default Downloads folder of your Windows operating system.\n\nFor restoration purposes, this tool is designed to automatically extract data from the .zip file it previously generated and put it back in the aforementioned folders.\n\nAll you need to do is to run the program as an administrator, select the location where you saved the .zip file earlier, and click "Restore" button!\n\nIf you attempt to execute the backup or recovery procedure without granting administrative privileges to Pandora qSHIELD Software, the program will not work as expected and might raise unexpected or weird errors. """

text3 = """This software is designed to automatically retrieve data from the following folders: "%localappdata%/qBittorrent" and "%appdata%/qBittorrent" after you click the "Start Backup" button.\n\nYou can choose the destination folder and partition for storing the backup. Ensure you have noted the drive letters of your Windows operating system.\n\nAfter you click the "Backup Data" button and have specified the location, you will find a "qSHIELD_Qbt_Backup {Date}.zip" file there which you will need to specify during the restoration process. If you haven't specified the backup location, qSHIELD will use the default Downloads folder of your Windows operating system.\n\nIf you attempt to execute the backup or recovery procedure without granting administrative privileges to Pandora qSHIELD Software, the program will not work as expected and might raise unexpected or weird errors."""

text4 = """This software is designed to automatically extract data from the .zip file it generated during the backup process and put it back in the following folders: "%localappdata%/qBittorrent" and "%appdata%/qBittorrent".\n\nAll you need to do is to run the program as an administrator, navigate to the location where you saved the .zip file earlier, select the file, and click "Start Restore" button!\n\nIf you attempt to execute the backup or recovery procedure without granting administrative privileges to Pandora qSHIELD Software, the program will not work as expected and might raise unexpected or weird errors."""


# print(text2)

